#ifndef ATOMIC_COUNTERS_H
#define ATOMIC_COUNTERS_H

/*
The token names defined here are acceptable
The values are dependant on the GLSL compiler
*/

/*Accepted by BindBufferBase and BindBufferRange*/
#define GL_ATOMIC_COUNTER_BUFFER		0x92C0

#define GL_ATOMIC_COUNTER_BUFFER_BINDING

#define GL_ATOMIC_COUNTER_BUFFER_START
#define GL_ATOMIC_COUNTER_

#define GL_ATOMICCOUNTERBUFFERDATASIZE
GLATOMICCOUNTERBUFFERACTIVEATOMICCOUNTERS
GLATOMICCOUNTERBUFFERACTIVEATOMICCOUNTERINDICES
GLATOMICCOUNTERBUFFERREFERENCEDBYVERTEXSHADER
GLATOMICCOUNTERBUFFERREFERENCEDBYTESSCONTROLSHADER
GLATOMICCOUNTERBUFFERREFERENCEDBYTESSEVALUATIONSHADER
GLATOMICCOUNTER

typedef unsigned int atomic_uint;
typedef int atomic_int;

unsigned int atomicCounterIncement(atomic_uint Inc);

#endif


